stages:
  - build
  - upload
  - release

variables:
  PACKAGE_NAME: "timesheet-${CI_COMMIT_TAG}-compressed.zip"
  PACKAGE_BINARY: "/builds/eFreniDeveloper/timesheet-api/target/${PACKAGE_NAME}"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/timesheet-api/${CI_COMMIT_TAG}"

create-artifact:
  stage: build
  image: maven:3.8.6-jdk-11
  cache:
    paths:
      - .m2/repository
  rules:
    - if: $CI_COMMIT_TAG
  artifacts:
    paths:
      - $PACKAGE_BINARY
  script:
    - 'mvn -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository clean install'

upload:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "${PACKAGE_BINARY}" "${PACKAGE_REGISTRY_URL}/${PACKAGE_NAME}"

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "running release_job"
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'Created using the release-cli'
    tag_name: '$CI_COMMIT_TAG'
    tag_message: 'Release $CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
