stages:

  - release

variables:
  PACKAGE_NAME: "timesheet-${CI_COMMIT_TAG}-compressed.zip"
  PACKAGE_BINARY: "/builds/eFreniDeveloper/timesheet-api/target/${PACKAGE_NAME}"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/timesheet-api/${CI_COMMIT_TAG}"


release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "running release_job"
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'Created using the release-cli $EXTRA_DESCRIPTION'
    tag_name: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: '$PACKAGE_NAME'
          url: '$PACKAGE_REGISTRY_URL/$PACKAGE_NAME'