services:
  timesheet-api:
    image: ghcr.io/e-freni-developer/timesheet-api:1.0.1-SNAPSHOT
    container_name: timesheet-api
    restart: unless-stopped
    ports:
      - 8500:8500
    env_file: ./env.list

  timesheet-ui:
    image: ghcr.io/e-freni-developer/timesheet-ui:1.0.0
    container_name: timesheet-ui
    ports:
      - 8501:80
    restart: unless-stopped

  postgres-database:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=timesheet
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data/

  apache_2.4:
    container_name: apache
    image: httpd:2.4
    restart: always
    ports:
      - 80:80
    volumes:
      - /opt/docker_volumes/apache/:/usr/local/apache2

volumes:
  # Windows is a shit -> execute: docker volume create postgres
  postgres:
    external: true
